
CREATE TABLE IF NOT EXISTS `rcm_purchase_limit_users` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ACTIVE` CHAR(1) NOT NULL DEFAULT 'N',
	`USER_ID` INT(18) NOT NULL,
	`LIMIT` INT(10) NOT NULL,
    `DATE_CREATE` DATETIME NULL,
	`CREATED_BY` INT(18) NULL,
    `TIMESTAMP_X` DATETIME NULL,
	`MODIFIED_BY` INT(18) NULL,
	PRIMARY KEY (`ID`)
);