CREATE TABLE IF NOT EXISTS `ac_api_projects` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `ACTIVE` CHAR(1) NOT NULL DEFAULT 'N',
	`NAME` VARCHAR(32) NOT NULL,
    `CODE` VARCHAR(32) NOT NULL,
    `LOGIN` VARCHAR(32) NOT NULL,
    `PASSWORD` VARCHAR(32) NOT NULL,
    `IP_ADDRESS` VARCHAR(15) NOT NULL,
    `DATE_CREATE` DATETIME NULL,
	`CREATED_BY` INT(18) NULL,
    `TIMESTAMP_X` DATETIME NULL,
	`MODIFIED_BY` INT(18) NULL,
	PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `ac_api_requests` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `PROJECT_ID` INT(18) NULL,
    `DATE_CREATE` DATETIME NULL,
    `REQUEST` TEXT NULL,
    PRIMARY KEY (`ID`)
);